# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
