# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20160905_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
