# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20160919_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='notes',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='serve_with',
            new_name='servings',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yields',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'Images/none/none.png', upload_to=b'Images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
