# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170526_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'none.png', upload_to=b'media'),
        ),
    ]
