# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20170526_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'none.png', upload_to=b'media/images'),
        ),
    ]
