# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20170526_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=b'Images/none.png', upload_to=b'Images'),
        ),
    ]
